version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-javagua
    restart: always
    ports:
      - "49869:5432"
    environment:
      POSTGRES_DB: javagua
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: javagua-app
    depends_on:
      - postgres
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/javagua
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret

volumes:
  postgres-data:

